config/routes.rb
Rails.application.routes.draw do

  # get 'rides/:id/suggestions', to: "suggestions#index", as: "suggestions"
  root to: 'pages#home'

  resources :pages, only: :index

  get 'final', to: "pages#final", as: "final"

  get 'myrequests', to: "myrequests#index", as: "myrequests"

  get 'myrequests/:id', to: "myrequests#show", as: "myrequest"

  get 'users', to: "users#index"

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :requests, only: [:index, :new, :create]
  resources :rides, only: [:index, :show, :new, :create ] do
    resources :suggestions, only: :index
    resources :offers, only: [:create,:update]
  end
  resources :users, only: [:show, :edit, :update ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/myrequests_controller.rb
class MyrequestsController < ApplicationController
  def index
    @myrequests = policy_scope(Request).where("user_id = #{current_user.id}")
    @offers = find_offers
    @markers_from = @offers.map do |offer|
      {
        lng: offer.ride.from_lng,
        lat: offer.ride.from_lat,
      }
    end
    if @offers != []
      @mapbounds = {
        min: { lat: @offers.map { |offer| offer.ride.from_lat }.max, lng: @offers.map { |offer| offer.ride.from_lng }.min },
        max: { lat: @offers.map { |offer| offer.ride.from_lat }.min, lng: @offers.map { |offer| offer.ride.from_lng }.max }
      }
    elsif @myrequests != []
      p @myrequests
      @markers_from = [{
        lng: @myrequests.first.from_lng,
        lat: @myrequests.first.from_lat,
      }]
      @mapbounds = {
        min: { lat: @myrequests.map { |myrequest| myrequest.from_lat }.max, lng: @myrequests.map { |myrequest| myrequest.from_lng }.min },
        max: { lat: @myrequests.map { |myrequest| myrequest.from_lat }.min, lng: @myrequests.map { |myrequest| myrequest.from_lng }.max }
      }

    end
  end

  def show
    @myrequest = Request.find(params[:id])
    @offers = Offer.where(request: @myrequest)
    @rides = @offers.map { |offer| offer.ride }
    authorize @myrequest


    @marker_from_passenger = {
      lng: @myrequest.from_lng,
      lat: @myrequest.from_lat,
      avatar: @myrequest.user.photo.url
    }


    @marker_to = {
      lng: @myrequest.to_lng,
      lat: @myrequest.to_lat
    }

    @drivers = @rides.map do |ride|
      {
        from: {
        lng: ride.from_lng,
        lat: ride.from_lat,
        },

        to: {
          lng: ride.to_lng,
          lat: ride.to_lat,
        },

        avatar: ride.user.photo.url,
        user_id: ride.user.id,
        ride_id: ride.id,
        first_name: ride.user.first_name,
        last_name: ride.user.last_name
      }
    end
  end

  private

  def find_offers
    matching_offers = []
    offers = Offer.all
    offers.each do |offer|
      if offer.request.user_id == current_user.id
        matching_offers << offer
      end
    end
    matching_offers
  end

end

app/views/myrequests/index.html.erb
<% content_for :title, "Your Requests" %>


<div class="myrequest-wrapper">
<!--   <div
  class="myrequest-map"
  id="mapmyrequestsindex"
  style="width: 100%;
  height: 50vh;"
  data-markers_from="<%= @markers_from.to_json %>"
  data-map_as="driver"
  data-mapbounds = "<%= @mapbounds.to_json %>"

  >
  </div> -->
  <div class="container">
    <div class="row myrequest-show">
      <div class="myrequests-title">
        <h1>Your Requests</h1>
        <p>See who would drive you</p>
      </div>
      <% @myrequests.each do |request| %>
      <div class="myrequest">
        <div class="myrequest-times">
          <h2><%= request.start_time.strftime("%d.%m.%y")%></h2>
          <h3><%= request.start_time.strftime("%H:%M") %> <i class="fas fa-arrow-circle-right"></i> <%= request.stop_time.strftime("%H:%M") %></h3>
        </div>
        <div class="trip-info">

          <div class="badge-offers"><%= request.offers.count %> Offers</div>
        </div>

        <%= link_to "", myrequest_path(id: request.id), class: "myrequest-link" %>
      </div>
      <% end %>
    </div>
</div>
</div>

app/views/myrequests/show.html.erb
<% content_for :title, "Request Information" %>

<div
id="mapshowmyrequest"
style="width: 100%; height: 50vh;"
data-marker_from_self="<%= @marker_from_passenger.to_json %>"
data-counterparts="<%= @drivers.to_json %>"
data-marker_to="<%= @marker_to.to_json %>"
data-rides_tags="<%= @rides.map { |ride| "select-ride-#{ride.id}"} %>"
>
</div>

<div class="myrequest-container">

  <div class="journey-info">
    <div class="full-width">
      <div class="myrequest-datetime">

        <h3><%= @myrequest.start_time.strftime("%d.%m.%y") %>
        </h3>
        <div>
          <h3>
           <%= @myrequest.start_time.strftime("%H:%M") %> <i class="fas fa-arrow-circle-right"></i>
           <%= @myrequest.stop_time.strftime("%H:%M") %>
         </h3>
       </div>

     </div>
     <div class="trip-info">

      <div class="trip-align-top"><p> <%= @myrequest.from_address.split(",").first %> to <%= @myrequest.to_address.split(",").first %>
      </p>
    </div>
    <div class="badge-offers"><%= @drivers.count %> Offers</div>
  </div>
</div>
</div>


<div class="list-group" role="tablist" aria-multiselectable="true">

  <% @offers.each do |offer| %>

  <div class="offer-card" id="select-ride-<%= offer.ride.id %>" ">
    <div class="card-header" id="heading-<%= offer.id %>" data-toggle="collapse" data-target="#collapse-<%= offer.id %>" aria-expanded="true" aria-controls="collapse-<%= offer.id %>">

      <div class="user-group">

        <%= cl_image_tag(offer.ride.user.photo, width:200, height:200, class:"avatar") %>
        <div class="ride-info">
            <p>
              <%= offer.ride.user.first_name %>
            </p>
            <div class="ride-info-icons">

            <p>

              <i class="fas fa-home"></i>

              <%= (offer.ride.departure_time - offer.duration_to_car).strftime("%I:%M")  %>
              <i class="fas fa-arrow-circle-right"></i>
              <%= (offer.ride.departure_time + offer.ride.duration + offer.duration_to_dest).strftime("%I:%M")  %>
            </p>

            <p>

              <i class="fas fa-stopwatch"></i>
              <%= (offer.duration_to_car + offer.ride.duration + offer.duration_to_dest) / 60 %> min

            </p>

          </div>
        </div>
      </div>

      <div class="status-group">
        <%= link_to ride_offer_path(offer.ride, offer, {confirmed: false}), data: {ride: "#{offer.ride.id}", offer: "#{offer.id}"}, class: "decline-btn", method: :put do %>
        <i class="icon fas fa-times fa-2x"></i>
        <% end %>
        <%= link_to ride_offer_path(offer.ride,offer, {confirmed: true}), :method=> :put do %>
        <i class="icon fas fa-check fa-2x"></i>
        <% end %>
      </div>
    </div>
    <div id="collapse-<%= offer.id %>" class="card-details collapse more-infos" aria-labelledby="heading-<%= offer.id %>" data-parent="#accordion">

      <div class="more-infos">
        <div class="highlight-container">

          <div class="highlight study">
            <div class="study-small"> STUDY </div>
            <%= offer.ride.user.course %> </div>

            <div class="highlight semester">

              <div class="semester-small"> SEMESTER </div>
              <%= offer.ride.user.semester %>
            </div>
          </div>

          <div class="info-container-pills">
            <% if offer.ride.user.music %>
            <div class="info-music info-pill">
              <% offer.ride.user.music.split(",").each do |music| %>
              <span class="badge badge-music badge-primary badge-pill"><%= music %></span>
              <% end %>
              <% end %>

              <% if offer.ride.user.hobby %>
              <% offer.ride.user.hobby.split(",").each do |hobby| %>
              <span class="badge badge-hobby badge-primary badge-pill"><%=  hobby %></span>
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="description-container">
            <p>
              <%=  offer.ride.user.description %>
            </p>
          </div>
        </div>
      </div>

    </div>
    <% end %>
  </div>


<div class="anti-grey">


</div>

</div>