config/routes.rb
Rails.application.routes.draw do

  # get 'rides/:id/suggestions', to: "suggestions#index", as: "suggestions"
  root to: 'pages#home'

  resources :pages, only: :index

  get 'final', to: "pages#final", as: "final"

  get 'myrequests', to: "myrequests#index", as: "myrequests"

  get 'myrequests/:id', to: "myrequests#show", as: "myrequest"

  get 'users', to: "users#index"

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :requests, only: [:index, :new, :create]
  resources :rides, only: [:index, :show, :new, :create ] do
    resources :suggestions, only: :index
    resources :offers, only: [:create,:update]
  end
  resources :users, only: [:show, :edit, :update ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <div class="navbar-opener">
    <i class="fas fa-bars"></i>
  </div>

<div class="navbar-wagon hidden animated fadeInDown">
  <div class="navbar-closer">
    <i class="fas fa-times"></i>
  </div>
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My Ride", "#", class: "navbar-wagon-item navbar-wagon-link navbar-wagon-text" %>
      <%= link_to "My Requests", myrequests_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-text" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown navbar-dropdown-icon">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <% if user_signed_in? %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu  animated slideInDown">
          <% ride = current_user.next_ride %>
          <% if ride %>
            <li>
              <%= link_to "My Ride", ride_path(ride), class: "navbar-wagon-item navbar-wagon-link" %>
            </li>
          <% end %>
          <li>
            <%= link_to "My Requests", myrequests_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      <% else %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>