config/routes.rb
Rails.application.routes.draw do

  # get 'rides/:id/suggestions', to: "suggestions#index", as: "suggestions"
  root to: 'pages#home'

  resources :pages, only: :index

  get 'final', to: "pages#final", as: "final"

  get 'myrequests', to: "myrequests#index", as: "myrequests"

  get 'myrequests/:id', to: "myrequests#show", as: "myrequest"

  get 'users', to: "users#index"

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :requests, only: [:index, :new, :create]
  resources :rides, only: [:index, :show, :new, :create ] do
    resources :suggestions, only: :index
    resources :offers, only: [:create,:update]
  end
  resources :users, only: [:show, :edit, :update ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def index
    @requests = policy_scope(Request)
    @ride = Ride.where(id: params["ride_id"]).first
    @suggestions = find_suggestions
  end


  private

  def find_suggestions
    scored_requests = []

    @requests.each do |request|
      if @ride.uni == request.uni && @ride.direction == request.direction && request.start_time < @ride.departure_time && request.stop_time > @ride.departure_time && request.user != @ride.user
        if calculate_score(request, @ride)
          data = compute_duration_and_distance(request, @ride)
          scored_requests<< [request, data] if data[:duration] <= 1200
        end
      end
    end
    sorted = scored_requests.sort_by { |array| array[1][:duration] }
    sorted.uniq! { |request| request[0][:user_id] }
    return sorted
  end

  def calculate_score(request, ride)
    max_distance = 1
    coordinates = get_lat_and_long(request, ride)
    coordinates[:request_lat]
    p distance_in_km = Math.sqrt( (((coordinates[:request_lat]-coordinates[:ride_lat]) * 71.44) ** 2) + (((coordinates[:request_lng] - coordinates[:ride_lng]) * 111.13 ) ** 2) )
    return distance_in_km < max_distance
  end
    # (request.from_lat - ride.from_lat).abs + (request.to_lat - ride.to_lat).abs + (request.from_lng - ride.from_lng).abs + (request.to_lng - ride.to_lng).abs

  def get_lat_and_long(request, ride)
    if request.direction == "to"
      request_lat = request.from_lat
      request_lng = request.from_lng
      ride_lat = ride.from_lat
      ride_lng = ride.from_lng
    else
      request_lat = request.to_lat
      request_lng = request.to_lng
      ride_lat = ride.to_lat
      ride_lng = ride.to_lng
    end
    return {
      request_lat: request_lat,
      request_lng: request_lng,
      ride_lat: ride_lat,
      ride_lng: ride_lng
    }
  end

  def compute_duration_and_distance(request, ride)
    rep = {}
    if(request.from_lat && request.from_lng && ride.from_lat && ride.from_lng)
      url_ride= "https://maps.googleapis.com/maps/api/distancematrix/json?origins=#{request.from_lat},#{request.from_lng}&destinations=#{ride.from_lat},#{ride.from_lng}&mode=driving&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
      distances_ride = JSON.parse(open(url_ride).read)
      unless distances_ride["rows"][0]["elements"][0]["status"] == "ZERO_RESULTS"
        rep[:duration] = distances_ride["rows"][0]["elements"][0]["duration"]["value"]
        rep[:distance] = distances_ride["rows"][0]["elements"][0]["distance"]["value"]
      end
    else
      rep[:duration] = 9999999
      rep[:distance] = 9999999
    end
    return rep
  end
end

app/views/suggestions/index.html.erb
<% content_for :title, "Select your passengers" %>





<div class="wrapper-suggestions">

  <div class="journey-info text-information">

    <h2>Passengers</h2>
    <p>Swipe right, up to <%= @ride.seats %> passengers</p>


  </div>

  <div class="wrapper-seats">


    <div class="loading-bar">
      <% @ride.seats.times do %>
      <div class="segment">
        <div class="dynamic" style="width: 0%;">
        </div>
      </div>
      <% end %>
    </div>

  </div>

  <div class="tinder-container">
    <form action=<%= ride_offers_path %> method="post">
      <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

      <ul>

        <% zindex = 10 %>
        <% @suggestions.each_with_index do |suggestion, i| %>
        <li class="swipe-card-element">

          <input type="checkbox" id=<%= "#{suggestion[0].id}" %> name=<%= "#{suggestion[0].id}"%> >
          <div class="offer-card" >
            <div class="card-header" ">

              <div class="suggestions-count">
               <h6 class="sugg-count-text">

                <%= "#{@suggestions.length-i}/#{@suggestions.length}" %>
              </h6>
            </div>
            <%= cl_image_tag(suggestion[0].user.photo, width:200, height:200, class:"avatar") %>
            <p>
              <%= suggestion[0].user.first_name  %>
            </p>

            <div class="highlight-container">

              <div class="highlight study">
                <div class="study-small"> STUDY </div>

                <%= suggestion[0].user.course %>
              </div>

              <div class="highlight semester">

                <div class="semester-small"> SEMESTER </div>
                <%= suggestion[0].user.semester %>
              </div>
            </div>


            <div class="info-container-pills info-music info-pill">
              <% if suggestion[0].user.music %>
              <% suggestion[0].user.music.split(",").each do |music| %>
              <span class="badge badge-music badge-primary badge-pill"><%= music %></span>
              <% end %>
              <% end %>

              <% if suggestion[0].user.hobby %>
              <% suggestion[0].user.hobby.split(",").each do |hobby| %>
              <span class="badge badge-hobby badge-primary badge-pill"><%=  hobby %></span>
              <% end %>
              <% end %>
            </div>

          </div>


<div class="status-group">
<!--         <div id="left-button"></div>
        <i class="icon fas fa-times fa-2x" ></i>
        <i class="icon fas fa-check fa-2x" id="right-button" ></i>
 -->
        <i class="icon fas fa-times fa-2x left-button" style="z-index= <%= zindex %>" ></i>
        <i class="icon fas fa-check fa-2x right-button" style="z-index= <%= zindex %>"></i>
</div>

        </div>


        <div class="max-passenger-cover hidden">
             <%= image_tag("logo.png", size:"100x100", class: "logo-home animated shake") %>
          <h3 class="animated shake">Your car is full!</h3>
        </div>

      </li>
      <% zindex -= 1 %>
      <% end %>

        <li class="no-more-passenger-cover hidden" data-nbsugg="<%= @suggestions.length %>">
          <div class="no-more-passenger-layout">

            <%= image_tag("logo.png", size:"100x100", class: "logo-home animated hinge") %>
            <div class="no-more-passenger-layout">

            <h3 class="animated ">no one else!</h3>
            <div>


            <p> <%= @ride.from_address.split(",").first %>
            </p>
            <p>

            <i class="fas fa-arrow-circle-right"></i>
             <%= @ride.to_address.split(",").first %>
                      </p>
            <p> <i class="fas fa-stopwatch"></i><%= @ride.departure_time.strftime("%I:%M") %></p>
            </div>
            </div>


          </div>

        </li>
    </ul>

</div>
</div>


    <div class="buttons">

        <input class="hidden animated bounceInUp" id="submit-button" type="submit"  value="Ride together">
<% if @suggestions.length.zero? %>

<%= link_to "Back to map", rides_path, class:"return-btn hidden animated bounceInUp" %>
<% end %>


    </div>

</form>

<%= javascript_pack_tag "tinder" %>