config/routes.rb
Rails.application.routes.draw do

  # get 'rides/:id/suggestions', to: "suggestions#index", as: "suggestions"
  root to: 'pages#home'

  resources :pages, only: :index

  get 'final', to: "pages#final", as: "final"

  get 'myrequests', to: "myrequests#index", as: "myrequests"

  get 'myrequests/:id', to: "myrequests#show", as: "myrequest"

  get 'users', to: "users#index"

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :requests, only: [:index, :new, :create]
  resources :rides, only: [:index, :show, :new, :create ] do
    resources :suggestions, only: :index
    resources :offers, only: [:create,:update]
  end
  resources :users, only: [:show, :edit, :update ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ride.rb
class Ride < ApplicationRecord
  before_validation :geocode_endpoints
  before_validation :compute_duration_and_distance


  belongs_to :user
  has_many :offers
  has_many :requests, through: :offers
  has_many :passengers, through: :requests, source: :user
  validates :seats, presence: true
  validates :seats, inclusion: {in: (1..8).to_a}


  validates :direction, inclusion: {in: ["to", "from", nil]}

  validates :uni, inclusion: {in: ["braunschweig", "aachen", "bayreuth"]}


  validates :departure_time, presence: true

  validates :from_lng, presence: true
  validates :from_lat, presence: true
  validates :to_lng, presence: true
  validates :to_lat, presence: true

  def geocode_endpoints
    if from_address
      geocoded = Geocoder.search(from_address).first
      if geocoded
        self.from_lat = geocoded.latitude
        self.from_lng = geocoded.longitude
      end
    end

    # Repeat for destination
    if to_address
      geocoded = Geocoder.search(to_address).first
      if geocoded
        self.to_lat = geocoded.latitude
        self.to_lng = geocoded.longitude
      end
    end
  end

  def compute_duration_and_distance
    if(self.from_lat && self.from_lng && self.to_lat && self.to_lng)
      url_ride= "https://maps.googleapis.com/maps/api/distancematrix/json?origins=#{self.from_lat},#{self.from_lng}&destinations=#{self.to_lat},#{self.to_lng}&mode=driving&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
      distances_ride = JSON.parse(open(url_ride).read)
      unless distances_ride["rows"][0]["elements"][0]["status"] == "ZERO_RESULTS"
        self.duration = distances_ride["rows"][0]["elements"][0]["duration"]["value"]
        self.distance = distances_ride["rows"][0]["elements"][0]["distance"]["value"]
      end
    else
      self.duration = 9999999
      self.distance = 9999999
    end
  end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :update_session

  def index
    @location = session[:location]
    @rides = policy_scope(Ride)
    @rides = @rides.where.not(from_lng: nil, from_lat: nil, to_lng: nil, to_lat: nil)
    @mapcenter = {
      lat: @location["lat"],
      lng: @location["lng"]
    } if session[:location]

    @drivers = @rides.map do |ride|
      {
        from: {
        lng: ride.from_lng,
        lat: ride.from_lat,
        },

        to: {
          lng: ride.to_lng,
          lat: ride.to_lat,
        },

        avatar: ride.user.photo.url,
        id: ride.user.id,
        first_name: ride.user.first_name,
        last_name: ride.user.last_name
      }
    end
    @mapbounds = {
      min: { lat: @rides.map { |ride| ride.from_lat }.max, lng: @rides.map { |ride| ride.from_lng }.min },
      max: { lat: @rides.map { |ride| ride.from_lat }.min, lng: @rides.map { |ride| ride.from_lng }.max }
    }

    @ride = Ride.new
    @request = Request.new
  end

  def show
    @ride = Ride.find(params[:id])
    authorize @ride

    @offers = Offer.where(ride: @ride).sort_by do |offer|
      sortvar = -1 if offer.confirmed
      sortvar = 0 if offer.confirmed.nil?
      sortvar = 1 unless offer.confirmed
      sortvar
    end
    @requests = @offers.map(&:request)

    @marker_from_driver = {
      lng: @ride.from_lng,
      lat: @ride.from_lat,
      icon: 'car.gif'
    }

    @marker_to = {
      lng: @ride.to_lng,
      lat: @ride.to_lat
    }

    @passengers = @requests.map do |request|
      {

      from: {
        lng: request.from_lng,
        lat: request.from_lat,
      },

      avatar: request.user.photo.url
      }




    end

    lats = [ @ride.from_lat, @ride.to_lat, @passengers.map { |passenger| passenger[:from][:lat] }].flatten
    lngs = [ @ride.from_lng, @ride.to_lng, @passengers.map { |passenger| passenger[:from][:lng] }].flatten


    @mapbounds = {
      min: { lat: lats.max, lng: lngs.min },
      max: { lat: lats.min, lng: lngs.max }
    }
  end

  def new
    @ride = Ride.new
    authorize @ride
  end

  def create
    uni = params.require(:ride)["uni"]
    if params.require(:ride)["direction"] == "from"
      to_address =  params.require(:ride)[:from_address]
      from_address = uni_address(uni)
    else
      to_address =  uni_address(uni)
      from_address = params.require(:ride)[:from_address]
    end
    params.require(:ride)[:from_address] = from_address
    params.require(:ride)[:to_address] = to_address

    @ride = Ride.create(ride_params)
    authorize @ride
    @ride.user_id = current_user.id

    if @ride.save
      redirect_to ride_suggestions_path(@ride)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def ride_params
    params.require(:ride).permit(:user_id, :seats,:from_address, :to_address, :departure_time, :uni, :direction)
  end

  def uni_address(uni)
    locations = {
      "bayreuth" => "Universitätsstraße 30, Bayreuth",
      "braunschweig"=> "Universitätsplatz 2, Braunschweig",
      "aachen" => "Templergraben 55, Aachen"
    }

    return locations[uni]
  end

  def update_session
    if params[:lat] != nil
      session[:location] = { "lat"=> params[:lat].to_f, "lng"=> params[:lng].to_f }
    end
  end
end

app/views/rides/destroy.html.erb
<h1>Rides#destroy</h1>
<p>Find me in app/views/rides/destroy.html.erb</p>

app/views/rides/edit.html.erb
<h1>Rides#edit</h1>
<p>Find me in app/views/rides/edit.html.erb</p>

app/views/rides/index.html.erb
<% content_for :title, "Share Your Ride or Find A Ride" %>

<div id="pingo-loading">
  <%= image_tag "logo.png", size:"100x100", class: "animated flip" %>
</div>
<div class="rides-index hidden">
    <div class="map-dummy animated fadeInUpBig">
      <div
      id="map-rides-index"
      style="width: 100%;
      height: 100%;"
      data-counterparts="<%= @drivers.to_json %>"
      data-mapbounds = "<%= @mapbounds.to_json %>"
      data-mapcenter = "<%= @mapcenter.to_json %>"


      ></div>
    </div>

    <div class="buttons-box form-opener animated fadeInUpBig">
        <a href="" class="btn index-buttons" id="new-ride-button">Share your ride</a>
        <a href="" class="btn index-buttons" id="new-request-button">Ride with new friends</a>
    </div>


    <div class="new-ride-form hidden" id="x-button">
      <div id="new-ride-close-button" class="close-button">
        <i class="fas fa-times" style="font-size:26px;"></i>
      </div>


      <%= form_for @ride, html: {class: "form-ride"} do |f| %>
      <div class="form-group flex-group">
        <% unless browser.platform.ios? %>
          <i class="far fa-clock"></i>
        <% end %>
        <%=  f.datetime_field :departure_time, value: "#{(Time.now + 1800).strftime("%Y-%m-%dT%H:%M")}", class: "form-control form-input" %>
      </div>

      <div class="form-group flex-group">
        <i class="fas fa-map-marker"></i>
        <%= f.text_field :from_address, class: "form-control form-input", placeholder: "Address" %>
      </div>

      <div class="to-from-radio">
        <div class="to-button">
          <%= f.radio_button :direction, "to", class:"hidden" %>
          <%= f.label :direction_to, "To Uni <i class='fas fa-angle-double-down'></i>".html_safe, class:"btn btn-standard"%>
        </div>
        <div class="from-button">
          <%= f.radio_button :direction, "from", class:"hidden"%>
          <%= f.label :direction_from, "Home <i class='fas fa-angle-double-up'></i>".html_safe, class:"btn btn-standard"%>
        </div>
      </div>

      <div class="form-group uni-select">
          <% if browser.platform.android? %>
            <i class="fas fa-graduation-cap"></i>
          <% end %>
          <%= f.select :uni,[['Universität Bayreuth','bayreuth'],['TU Braunschweig','braunschweig'],['RWTH Aachen','aachen']], {},{class: "form-control form-input"} %>
      </div>

      <div class="form-group flex-group">
        <i class="fas fa-users"></i>
        <%= f.number_field :seats, as: :integer, class: "form-control form-input", placeholder: "Number of seats" %>
      </div>

      <%= f.submit "Share your ride", class: "btn index-buttons" %>
      <% end %>

    </div>



    <div class="new-request-form hidden" id="x-button">
      <div id="new-request-close-button" class="close-button">
        <i class="fas fa-times" style="font-size:26px;"></i>
      </div>


      <%= form_for @request, html: {class: "form-ride"} do |f| %>

      <div class="form-group date_field flex-group">
          <% unless browser.platform.ios? %>
            <i class="far fa-calendar-alt"></i>
          <% end %>
          <%=  f.datetime_field :start_time, value: "#{Time.now.strftime("%Y-%m-%dT%H:%M")}", class: "form-control form-input"%>
      </div>

      <div class="form-group to_time_field time_field flex-group">
        <% unless browser.platform.ios? %>
          <i class="far fa-clock"></i>
        <% end %>
        <%=  f.time_field :stop_time, value: "#{(Time.now + 3600).strftime("%H:%M")}", class: "form-control form-input" %>
      </div>

      <div class="form-group flex-group">
        <i class="fas fa-map-marker"></i>
        <%= f.text_field :from_address, class: "form-control form-input", placeholder: "from here" %>
      </div>

      <div class="to-from-radio">
        <div class="to-button">
          <%= f.radio_button :direction, "to", class:"hidden" %>
          <%= f.label :direction_to, "To Uni <i class='fas fa-angle-double-down'></i>".html_safe, class:"btn btn-standard"%>
        </div>
        <div class="from-button">
          <%= f.radio_button :direction, "from", class:"hidden"%>
          <%= f.label :direction_from, "Home <i class='fas fa-angle-double-up'></i>".html_safe, class:"btn btn-standard"%>
        </div>
      </div>


      <div class="form-group uni-select">
          <% if browser.platform.android? %>
            <i class="fas fa-graduation-cap"></i>
          <% end %>
          <%= f.select :uni,[['Universität Bayreuth','bayreuth'],['TU Braunschweig','braunschweig'],['RWTH Aachen','aachen']], {},{class: "form-control form-input"} %>
      </div>

      <%= f.submit "Share your ride", class: "btn index-buttons" %>
      <% end %>
    </div>
  </div>

</div>

<% content_for :after_js do %>
<script>
  $(document).ready(function() {

    setTimeout(function(){
      $('#pingo-loading').fadeOut();
      $('.rides-index').removeClass('hidden');
    }, 1500);
  });
</script>
<% end %>

app/views/rides/new.html.erb
<div class="container">
  <h1>Share your ride!</h1>
  <h2 style="color: red;">Check your inputs</h2>
  <div>
    <%= form_for @ride, html: {class: "form-ride"} do |f| %>
    <div class="form-group flex-group">
      <!-- <%= f.label :departure_time, "Departure" %> -->
      <i class="far fa-clock"></i>
      <%=  f.datetime_field :departure_time, value: "#{(Time.now + 1800).strftime("%Y-%m-%dT%H:%M")}", class: "form-control" %>
    </div>
    <div class="form-group flex-group">
      <!-- <%= f.label :from_address, "From" %> -->
      <i class="fas fa-map-marker"></i>
      <%= f.text_field :from_address, class: "form-control", placeholder: "from here" %>
    </div>

    <div class="form-group flex-group">
      <!-- <%= f.label :to_address, "To" %> -->
      <i class="fas fa-compass"></i>
      <%= f.text_field :to_address, class: "form-control", placeholder: "to there" %>
    </div>

    <div class="form-group flex-group">
      <i class="fas fa-users"></i>
      <%= f.number_field :seats, as: :integer, class: "form-control", placeholder: "Number of seats" %>
    </div>

    <%= f.submit "share your ride", class: "btn index-buttons" %>
    <% end %>
  </div>
</div>

app/views/rides/show.html.erb
<% content_for :title, "Ride Information"%>

<div
id="mapshow"
style="width: 100vw;
height: 406px;"
data-marker_from_self="<%= @marker_from_driver.to_json %>"
data-counterparts="<%= @passengers.to_json %>"
data-marker_to="<%= @marker_to.to_json %>"
data-map_as="driver"
data-mapbounds = "<%= @mapbounds.to_json %>"
>
</div>


<div class="rideshow-container">
  <div class="journey-info" data-toggle="collapse" data-target="#collapse-driver" aria-expanded="true" aria-controls="collapse-driver">
    <div class="text-information">
      <h2><%= @ride.departure_time.strftime("%H:%M") %></h2>
      <p><%= @ride.from_address.split(",")[0] %></p>
    </div>
      <%= cl_image_tag(@ride.user.photo, class: "avatar") %>
      <p class="says-driver"><%= @ride.user.first_name %></p>
  </div>
  <div class="drivers-card">
    <div id="collapse-driver" class="collapse" aria-labelledby="heading-driver" data-parent="#accordion">

      <div class="more-infos">
        <h4><%= @ride.user.first_name %></h4>

        <div class="highlight-container">

          <div class="highlight study">
            <div class="study-small">
              STUDY
            </div>
            <%= @ride.user.course %>
          </div>

          <div class="highlight semester">
            <div class="semester-small">
              SEMESTER
            </div>
            <%= @ride.user.semester %>
          </div>
        </div>

        <div class="info-container-pills">
          <% if @ride.user.music %>
          <div class="info-music info-pill">
            <% @ride.user.music.split(",").each do |music| %>
            <span class="badge badge-music badge-primary badge-pill"><%= music %></span>
            <% end %>
            <% end %>

            <% if @ride.user.hobby %>
            <% @ride.user.hobby.split(",").each do |hobby| %>
            <span class="badge badge-hobby-driver badge-primary badge-pill"><%=  hobby %></span>
            <% end %>
          </div>
          <% end %>
        </div>
        <div class="description-container">
          <p>
            <%=  @ride.user.description %>
          </p>
        </div>


      </div>
    </div>
  </div>
  <div class="list-group">

    <% @offers.each do |offer| %>

    <div data-toggle="collapse" data-target="#collapse-<%= offer.id %>" aria-expanded="true" aria-controls="collapse-<%= offer.id %>">
      <div class="offer-card">
        <div class="card-header" id="heading-<%= offer.id %>">

          <div class="user-group">

            <%= cl_image_tag(offer.request.user.photo, width:200, height:200, class:"avatar") %>
            <div class="ride-info">

              <p>
                <%=  offer.request.user.first_name %>
              </p>

              <div class="ride-info-icons">
                <p>
                  <%= image_tag("walker.png", class: "ride-symbols") %>
                  <%= offer.duration_to_car / 60 %> min
                </p>
              </div>
            </div>

          </div>

          <div class="status-group">
            <% if offer.confirmed %>
            <i class="icon fas fa-check fa-2x"></i>
            <% elsif offer.confirmed.nil? %>
            <i class="icon fas fa-question fa-2x" style="color: gray" ></i>
            <% elsif offer.confirmed == false %>
            <i class="icon fas fa-times fa-2x"></i>
            <% end %>
          </div>
        </div>
        <div id="collapse-<%= offer.id %>" class="collapse full-width card-body" aria-labelledby="heading-<%= offer.id %>" data-parent="#accordion">

          <div class="more-infos">
            <div class="highlight-container">

              <div class="highlight study">
                <div class="study-small"> STUDY </div>
                <%= offer.request.user.course %> </div>

                <div class="highlight semester">

                  <div class="semester-small"> SEMESTER </div>
                  <%= offer.request.user.semester %>
                </div>
              </div>

              <div class="info-container-pills">
                <% if offer.request.user.music %>
                <div class="info-music info-pill">
                  <% offer.request.user.music.split(",").each do |music| %>
                  <span class="badge badge-music badge-primary badge-pill"><%= music %></span>
                  <% end %>
                  <% end %>

                  <% if offer.request.user.hobby %>
                  <% offer.request.user.hobby.split(",").each do |hobby| %>
                  <span class="badge badge-hobby badge-primary badge-pill"><%=  hobby %></span>
                  <% end %>
                </div>
                <% end %>
              </div>
              <div class="description-container">
                <p>
                  <%=  offer.request.user.description %>
                </p>
              </div>
            </div>
          </div>
        </div>

      </div>
      <% end %>

        <%= link_to("Done",final_path, class:"offer-card btn", id:"done-button")%>
    </div>


  </div>

app/views/rides/update.html.erb
<h1>Rides#update</h1>
<p>Find me in app/views/rides/update.html.erb</p>